server:
  port: 8090

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/requests
    username: ismael
    password: Test123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
