server:
  port: 8083

---

spring:
  application:
    name: mvc-pqr-img

  datasource:
    url: jdbc:postgresql://localhost:5433/pqrs-img
    username: ismael
    password: Test123
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true
